name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

env:
  GO_VERSION: ^1.21.5
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: sha-${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Tag image as latest
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push latest image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
