name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GO_VERSION: ^1.21.5
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  package:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Pack
        uses: buildpacks/github-actions/setup-pack@v5.5.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=sha,format=long

      - name: Build images
        run: |
          pack build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --builder gcr.io/buildpacks/builder:v1 \
            --env GOOGLE_FUNCTION_SIGNATURE_TYPE=http \
            --env GOOGLE_FUNCTION_TARGET=ModProxy

      - name: Tag and push images
        run: |
          echo "${{ steps.meta.outputs.tags }}" | while read tag
          do
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} $tag
          done
          docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --all-tags
