name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GO_VERSION: ^1.21.5

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
